import type { CardioActivity } from "./types";

export const CARDIO_ACTIVITIES: CardioActivity[] = [
  {
    id: "walking",
    name: "Walking",
    intensity: "low",
    met: 3.5,
    defaultMinutes: 30,
    beginner: "20 minutes at a comfortable, conversational pace.",
    intermediate: "40 minutes at a brisk pace.",
    advanced: "60 minutes brisk, or add a weighted vest or backpack.",
    warmUp: "3 minutes of easy walking.",
    coolDown: "3 minutes of easy walking plus calf and hip flexor stretches.",
    notes: "Easy to recover from and simple to repeat most days.",
  },
  {
    id: "incline-walk",
    name: "Incline Treadmill Walk",
    intensity: "low",
    met: 5.3,
    defaultMinutes: 30,
    beginner: "20 minutes at 5% incline, comfortable speed.",
    intermediate: "30 minutes at 8–10% incline.",
    advanced: "45 minutes at 10–12% incline without holding the rails.",
    warmUp: "4 minutes flat walking.",
    coolDown: "4 minutes flat walking.",
    notes: "Low impact but raises heart rate quickly.",
  },
  {
    id: "easy-cycling",
    name: "Easy Cycling",
    intensity: "low",
    met: 4,
    defaultMinutes: 35,
    beginner: "20 minutes at light resistance.",
    intermediate: "40 minutes at steady easy effort.",
    advanced: "60–90 minutes as recovery work.",
    warmUp: "5 minutes very light pedalling.",
    coolDown: "5 minutes light pedalling, then quad stretch.",
    notes: "Very joint friendly.",
  },
  {
    id: "easy-swim",
    name: "Easy Swimming",
    intensity: "low",
    met: 5.8,
    defaultMinutes: 30,
    beginner: "10 × 25 m with generous rest.",
    intermediate: "20 continuous minutes at an easy pace.",
    advanced: "35–45 minutes mixing strokes.",
    warmUp: "100 m easy swimming plus shoulder circles.",
    coolDown: "100 m very easy swimming.",
    notes: "Full-body and low impact.",
  },
  {
    id: "jogging",
    name: "Jogging",
    intensity: "moderate",
    met: 7,
    defaultMinutes: 30,
    beginner: "Run 1 minute / walk 2 minutes, repeat 8 times.",
    intermediate: "25–30 minutes continuous at conversational pace.",
    advanced: "45–60 minutes at a steady aerobic pace.",
    warmUp: "5 minutes brisk walking and leg swings.",
    coolDown: "5 minutes walking and light stretching.",
    notes: "Build weekly mileage gradually to protect joints and tendons.",
  },
  {
    id: "cycling",
    name: "Cycling",
    intensity: "moderate",
    met: 8,
    defaultMinutes: 40,
    beginner: "20 minutes at moderate resistance.",
    intermediate: "40 minutes steady.",
    advanced: "75 minutes with rolling terrain.",
    warmUp: "5 minutes easy spinning.",
    coolDown: "5 minutes easy spinning.",
    notes: "Adjust the saddle height so your knee stays slightly bent at the bottom.",
  },
  {
    id: "rowing",
    name: "Rowing",
    intensity: "moderate",
    met: 7,
    defaultMinutes: 25,
    beginner: "5 × 3 minutes with 1 minute rest.",
    intermediate: "20 minutes continuous.",
    advanced: "30–40 minutes steady state.",
    warmUp: "3 minutes light rowing focusing on sequence.",
    coolDown: "3 minutes light rowing.",
    notes: "Sequence is legs, then body, then arms — reverse on the return.",
  },
  {
    id: "elliptical",
    name: "Elliptical",
    intensity: "moderate",
    met: 5,
    defaultMinutes: 30,
    beginner: "15 minutes at light resistance.",
    intermediate: "30 minutes steady.",
    advanced: "45 minutes with resistance changes every 5 minutes.",
    warmUp: "4 minutes easy.",
    coolDown: "4 minutes easy.",
    notes: "Useful when you want moderate work with minimal impact.",
  },
  {
    id: "running",
    name: "Running",
    intensity: "high",
    met: 9.8,
    defaultMinutes: 30,
    beginner: "15 minutes at an easy but continuous pace.",
    intermediate: "30 minutes at a moderate pace.",
    advanced: "45+ minutes, or a tempo run.",
    warmUp: "6 minutes easy jogging plus drills.",
    coolDown: "6 minutes easy jogging then walking.",
    notes: "Keep most running easy; hard sessions should be a minority of the week.",
  },
  {
    id: "run-intervals",
    name: "Running Intervals",
    intensity: "high",
    met: 11,
    defaultMinutes: 25,
    beginner: "6 × 30 seconds fast, 90 seconds walking.",
    intermediate: "8 × 60 seconds hard, 90 seconds easy.",
    advanced: "6 × 3 minutes hard, 2 minutes easy.",
    warmUp: "8 minutes easy jogging plus strides.",
    coolDown: "8 minutes easy jogging.",
    notes: "Limit hard interval sessions to one to two per week.",
  },
  {
    id: "hill-intervals",
    name: "Hill Intervals",
    intensity: "high",
    met: 10.5,
    defaultMinutes: 25,
    beginner: "6 × 20 seconds uphill, walk down.",
    intermediate: "8 × 45 seconds uphill, walk down.",
    advanced: "10 × 60 seconds uphill, jog down.",
    warmUp: "8 minutes easy jogging.",
    coolDown: "6 minutes easy jogging.",
    notes: "Hills reduce impact forces compared with flat sprinting.",
  },
  {
    id: "bike-intervals",
    name: "Cycling Intervals",
    intensity: "high",
    met: 10,
    defaultMinutes: 25,
    beginner: "8 × 20 seconds hard, 100 seconds easy.",
    intermediate: "10 × 40 seconds hard, 80 seconds easy.",
    advanced: "5 × 3 minutes hard, 3 minutes easy.",
    warmUp: "8 minutes progressive spinning.",
    coolDown: "6 minutes easy spinning.",
    notes: "Low impact way to train at higher intensities.",
  },
  {
    id: "row-intervals",
    name: "Rowing Intervals",
    intensity: "high",
    met: 9.5,
    defaultMinutes: 22,
    beginner: "6 × 250 m with 90 seconds rest.",
    intermediate: "8 × 500 m with 2 minutes rest.",
    advanced: "5 × 1000 m with 3 minutes rest.",
    warmUp: "5 minutes easy rowing with technique focus.",
    coolDown: "5 minutes easy rowing.",
    notes: "Keep the stroke rate controlled rather than rushing the slide.",
  },
];

export function getCardioActivity(id: string): CardioActivity | undefined {
  return CARDIO_ACTIVITIES.find((activity) => activity.id === id);
}
