import type { Exercise, MuscleGroup } from "./types";

type ExerciseSeed = Omit<Exercise, "breathing"> & { breathing?: string };

const DEFAULT_BREATHING =
  "Inhale as you lower or lengthen the muscle, brace, then exhale as you push or pull through the hardest part of the rep.";

function make(seed: ExerciseSeed): Exercise {
  return { breathing: DEFAULT_BREATHING, ...seed };
}

export const MUSCLE_GROUPS: { key: MuscleGroup; label: string }[] = [
  { key: "chest", label: "Chest" },
  { key: "back", label: "Back" },
  { key: "shoulders", label: "Shoulders" },
  { key: "biceps", label: "Biceps" },
  { key: "triceps", label: "Triceps" },
  { key: "legs", label: "Legs" },
  { key: "core", label: "Core" },
];

export const EXERCISES: Exercise[] = [
  make({
    id: "bench-press",
    name: "Barbell Bench Press",
    group: "chest",
    targets: ["Pectorals", "Front deltoids", "Triceps"],
    equipment: ["barbell"],
    difficulty: "intermediate",
    defaultSets: 4,
    defaultReps: "6-10",
    restSeconds: 150,
    tempo: "2-0-1",
    met: 5,
    compound: true,
    setup: [
      "Lie on the bench with your eyes under the bar.",
      "Plant your feet and set a slight natural arch in your lower back.",
      "Grip the bar slightly wider than shoulder width.",
    ],
    steps: [
      "Unrack the bar and hold it over your upper chest with straight arms.",
      "Lower the bar under control to the lower chest.",
      "Keep your elbows at roughly 45–70 degrees from your torso.",
      "Touch the chest lightly, then press back to the start.",
      "Keep your shoulder blades pulled back throughout.",
    ],
    formTips: [
      "Keep your wrists stacked over your elbows.",
      "Press your feet into the floor for stability.",
      "Use a spotter or safety pins when training close to failure.",
    ],
    mistakes: [
      "Bouncing the bar off the chest",
      "Flaring the elbows straight out to the sides",
      "Lifting the hips off the bench",
    ],
    easier: "Dumbbell bench press or push-up",
    harder: "Pause bench press",
  }),
  make({
    id: "incline-db-press",
    name: "Incline Dumbbell Press",
    group: "chest",
    targets: ["Upper pectorals", "Front deltoids"],
    equipment: ["dumbbell"],
    difficulty: "beginner",
    defaultSets: 3,
    defaultReps: "8-12",
    restSeconds: 120,
    met: 5,
    compound: true,
    setup: [
      "Set the bench to roughly 30 degrees.",
      "Sit down with the dumbbells resting on your thighs.",
      "Kick them up as you lie back.",
    ],
    steps: [
      "Start with the dumbbells above your upper chest.",
      "Lower them until your elbows are slightly below shoulder level.",
      "Keep a controlled tempo.",
      "Press back up without clashing the dumbbells together.",
    ],
    formTips: [
      "Keep your shoulder blades retracted.",
      "Control the descent instead of dropping the weight.",
    ],
    mistakes: ["Setting the bench too steep", "Very short range of motion"],
    easier: "Machine chest press",
    harder: "Incline barbell press",
  }),
  make({
    id: "push-up",
    name: "Push-Up",
    group: "chest",
    targets: ["Pectorals", "Triceps", "Core"],
    equipment: ["bodyweight"],
    difficulty: "beginner",
    defaultSets: 3,
    defaultReps: "8-20",
    restSeconds: 75,
    met: 4,
    compound: true,
    setup: [
      "Place your hands slightly wider than shoulder width.",
      "Set your body in a straight line from head to heels.",
    ],
    steps: [
      "Brace your core and squeeze your glutes.",
      "Lower your chest towards the floor.",
      "Keep your elbows at around 45 degrees.",
      "Press back up to full elbow extension.",
    ],
    formTips: ["Keep your hips level.", "Look slightly ahead, not straight down."],
    mistakes: ["Sagging hips", "Head dropping before the chest"],
    easier: "Incline push-up against a bench",
    harder: "Weighted or deficit push-up",
  }),
  make({
    id: "cable-fly",
    name: "Cable Fly",
    group: "chest",
    targets: ["Pectorals"],
    equipment: ["cable"],
    difficulty: "beginner",
    defaultSets: 3,
    defaultReps: "12-15",
    restSeconds: 75,
    met: 4,
    compound: false,
    setup: ["Set both pulleys at or slightly above shoulder height.", "Take a short staggered stance."],
    steps: [
      "Hold the handles with a soft bend in the elbows.",
      "Bring your hands together in front of your chest.",
      "Squeeze briefly at the end position.",
      "Return under control until you feel a stretch.",
    ],
    formTips: ["Keep the elbow angle fixed.", "Move from the shoulder, not the elbow."],
    mistakes: ["Turning it into a press", "Using momentum from the torso"],
    easier: "Pec deck machine",
    harder: "Single-arm cable fly with a pause",
  }),
  make({
    id: "pec-deck",
    name: "Pec Deck",
    group: "chest",
    targets: ["Pectorals"],
    equipment: ["machine"],
    difficulty: "beginner",
    defaultSets: 3,
    defaultReps: "12-15",
    restSeconds: 60,
    met: 4,
    compound: false,
    setup: ["Adjust the seat so the handles sit at chest height."],
    steps: [
      "Press your back into the pad.",
      "Bring the handles together smoothly.",
      "Pause for a beat, then return slowly.",
    ],
    formTips: ["Avoid shrugging your shoulders.", "Keep the movement smooth."],
    mistakes: ["Slamming the weight stack", "Excessive range that strains the shoulder"],
    easier: "Lighter load with a longer pause",
    harder: "One-and-a-half reps",
  }),
  make({
    id: "pull-up",
    name: "Pull-Up",
    group: "back",
    targets: ["Lats", "Mid-back", "Biceps"],
    equipment: ["bodyweight"],
    difficulty: "advanced",
    defaultSets: 4,
    defaultReps: "4-10",
    restSeconds: 150,
    met: 6,
    compound: true,
    setup: ["Grip the bar slightly wider than shoulder width.", "Hang with active shoulders."],
    steps: [
      "Pull your shoulder blades down first.",
      "Drive your elbows down towards your ribs.",
      "Bring your chin above the bar.",
      "Lower under control to a full hang.",
    ],
    formTips: ["Avoid swinging.", "Think about pulling the bar to you."],
    mistakes: ["Partial range of motion", "Kipping without intent"],
    easier: "Band-assisted pull-up or lat pulldown",
    harder: "Weighted pull-up",
  }),
  make({
    id: "lat-pulldown",
    name: "Lat Pulldown",
    group: "back",
    targets: ["Lats", "Biceps"],
    equipment: ["machine", "cable"],
    difficulty: "beginner",
    defaultSets: 3,
    defaultReps: "10-12",
    restSeconds: 90,
    met: 5,
    compound: true,
    setup: ["Set the thigh pad snugly.", "Grip the bar wider than shoulder width."],
    steps: [
      "Sit tall with a slight backward lean.",
      "Pull the bar to your upper chest.",
      "Squeeze your back at the bottom.",
      "Let the bar rise slowly to a full stretch.",
    ],
    formTips: ["Lead with the elbows.", "Keep your chest up."],
    mistakes: ["Leaning back excessively", "Pulling behind the neck"],
    easier: "Lighter load, neutral grip",
    harder: "Single-arm pulldown",
  }),
  make({
    id: "barbell-row",
    name: "Barbell Row",
    group: "back",
    targets: ["Mid-back", "Lats", "Rear deltoids"],
    equipment: ["barbell"],
    difficulty: "intermediate",
    defaultSets: 4,
    defaultReps: "6-10",
    restSeconds: 150,
    met: 6,
    compound: true,
    setup: ["Hinge at the hips with a flat back.", "Hold the bar just outside your knees."],
    steps: [
      "Brace your core hard.",
      "Row the bar towards your lower ribs.",
      "Pause briefly at the top.",
      "Lower under control without rounding your back.",
    ],
    formTips: ["Keep your torso angle stable.", "Choose a weight you can control."],
    mistakes: ["Standing up with each rep", "Rounding the lower back"],
    easier: "Chest-supported row",
    harder: "Pendlay row from the floor",
  }),
  make({
    id: "db-row",
    name: "Single-Arm Dumbbell Row",
    group: "back",
    targets: ["Lats", "Mid-back"],
    equipment: ["dumbbell"],
    difficulty: "beginner",
    defaultSets: 3,
    defaultReps: "8-12",
    restSeconds: 90,
    met: 5,
    compound: true,
    setup: ["Place one knee and hand on a bench.", "Keep your back flat and hips square."],
    steps: [
      "Let the dumbbell hang with an active shoulder.",
      "Row it towards your hip.",
      "Squeeze, then lower with control.",
    ],
    formTips: ["Avoid twisting the torso.", "Keep the neck neutral."],
    mistakes: ["Yanking the weight", "Rotating the spine to gain range"],
    easier: "Seated cable row",
    harder: "Heavier load with a pause at the top",
  }),
  make({
    id: "seated-row",
    name: "Seated Cable Row",
    group: "back",
    targets: ["Mid-back", "Lats", "Biceps"],
    equipment: ["cable", "machine"],
    difficulty: "beginner",
    defaultSets: 3,
    defaultReps: "10-12",
    restSeconds: 90,
    met: 5,
    compound: true,
    setup: ["Sit with a slight knee bend and a tall chest."],
    steps: [
      "Pull the handle to your abdomen.",
      "Keep your torso still.",
      "Return slowly to a full stretch.",
    ],
    formTips: ["Squeeze the shoulder blades together.", "Avoid rocking."],
    mistakes: ["Using the lower back to swing", "Shrugging at the top"],
    easier: "Lighter load with a neutral grip",
    harder: "Single-arm variation",
  }),
  make({
    id: "overhead-press",
    name: "Barbell Overhead Press",
    group: "shoulders",
    targets: ["Deltoids", "Triceps", "Upper chest"],
    equipment: ["barbell"],
    difficulty: "intermediate",
    defaultSets: 4,
    defaultReps: "5-8",
    restSeconds: 150,
    met: 5,
    compound: true,
    setup: ["Stand with feet hip-width apart.", "Hold the bar at shoulder height with wrists stacked."],
    steps: [
      "Brace your core and squeeze your glutes.",
      "Press the bar overhead, moving your head slightly back then through.",
      "Lock out with the bar over the mid-foot.",
      "Lower under control to the shoulders.",
    ],
    formTips: ["Avoid over-arching your lower back.", "Keep your ribs down."],
    mistakes: ["Leaning back excessively", "Pressing around the head instead of through"],
    easier: "Seated dumbbell shoulder press",
    harder: "Strict tempo press or push press for overload",
  }),
  make({
    id: "db-shoulder-press",
    name: "Dumbbell Shoulder Press",
    group: "shoulders",
    targets: ["Deltoids", "Triceps"],
    equipment: ["dumbbell"],
    difficulty: "beginner",
    defaultSets: 3,
    defaultReps: "8-12",
    restSeconds: 90,
    met: 5,
    compound: true,
    setup: ["Sit with back support and the dumbbells at shoulder height."],
    steps: [
      "Press the dumbbells up and slightly together.",
      "Stop just short of clashing them.",
      "Lower to ear level under control.",
    ],
    formTips: ["Keep the wrists neutral.", "Do not bounce out of the bottom."],
    mistakes: ["Excessive arching", "Half repetitions"],
    easier: "Machine shoulder press",
    harder: "Standing press or single-arm press",
  }),
  make({
    id: "lateral-raise",
    name: "Lateral Raise",
    group: "shoulders",
    targets: ["Side deltoids"],
    equipment: ["dumbbell", "cable"],
    difficulty: "beginner",
    defaultSets: 3,
    defaultReps: "12-20",
    restSeconds: 60,
    met: 3,
    compound: false,
    setup: ["Stand tall with a light dumbbell in each hand."],
    steps: [
      "Raise your arms out to the sides to shoulder height.",
      "Keep a soft elbow bend.",
      "Lower slowly over two seconds.",
    ],
    formTips: ["Lead with the elbows, not the hands.", "Use a weight you can control."],
    mistakes: ["Swinging with the torso", "Shrugging the traps"],
    easier: "Seated lateral raise",
    harder: "Cable lateral raise with a pause",
  }),
  make({
    id: "rear-delt-fly",
    name: "Rear-Delt Fly",
    group: "shoulders",
    targets: ["Rear deltoids", "Upper back"],
    equipment: ["dumbbell", "machine"],
    difficulty: "beginner",
    defaultSets: 3,
    defaultReps: "12-20",
    restSeconds: 60,
    met: 3,
    compound: false,
    setup: ["Hinge forward with a flat back or use a chest-supported bench."],
    steps: [
      "Let the dumbbells hang below your chest.",
      "Raise them out to the sides.",
      "Squeeze briefly and lower slowly.",
    ],
    formTips: ["Keep the neck relaxed.", "Think wide, not up."],
    mistakes: ["Turning it into a row", "Using too much weight"],
    easier: "Machine reverse fly",
    harder: "Pause at the top of each rep",
  }),
  make({
    id: "face-pull",
    name: "Face Pull",
    group: "shoulders",
    targets: ["Rear deltoids", "Rotator cuff", "Mid-back"],
    equipment: ["cable", "band"],
    difficulty: "beginner",
    defaultSets: 3,
    defaultReps: "12-20",
    restSeconds: 60,
    met: 3,
    compound: false,
    setup: ["Set the pulley at upper-chest height with a rope."],
    steps: [
      "Pull the rope towards your forehead.",
      "Separate your hands as you pull.",
      "Pause, then return slowly.",
    ],
    formTips: ["Keep the elbows high.", "Stay tall through the chest."],
    mistakes: ["Leaning back to move the weight", "Going too heavy"],
    easier: "Band face pull",
    harder: "Half-kneeling face pull",
  }),
  make({
    id: "db-curl",
    name: "Dumbbell Curl",
    group: "biceps",
    targets: ["Biceps"],
    equipment: ["dumbbell"],
    difficulty: "beginner",
    defaultSets: 3,
    defaultReps: "8-12",
    restSeconds: 75,
    met: 3,
    compound: false,
    setup: ["Stand tall with dumbbells at your sides."],
    steps: [
      "Curl the weight while keeping your elbows near your ribs.",
      "Squeeze at the top.",
      "Lower over two to three seconds.",
    ],
    formTips: ["Keep the shoulders still.", "Avoid swinging the torso."],
    mistakes: ["Using momentum", "Cutting the range short"],
    easier: "Seated curl",
    harder: "Incline dumbbell curl",
  }),
  make({
    id: "barbell-curl",
    name: "Barbell Curl",
    group: "biceps",
    targets: ["Biceps"],
    equipment: ["barbell"],
    difficulty: "beginner",
    defaultSets: 3,
    defaultReps: "8-12",
    restSeconds: 75,
    met: 3,
    compound: false,
    setup: ["Hold the bar shoulder-width with an underhand grip."],
    steps: ["Curl the bar to chest height.", "Pause briefly.", "Lower under control."],
    formTips: ["Keep your elbows pinned.", "Brace your core."],
    mistakes: ["Leaning back", "Bouncing at the bottom"],
    easier: "EZ-bar curl",
    harder: "Strict curl against a wall",
  }),
  make({
    id: "hammer-curl",
    name: "Hammer Curl",
    group: "biceps",
    targets: ["Biceps", "Brachialis", "Forearms"],
    equipment: ["dumbbell"],
    difficulty: "beginner",
    defaultSets: 3,
    defaultReps: "10-12",
    restSeconds: 60,
    met: 3,
    compound: false,
    setup: ["Hold dumbbells with a neutral grip."],
    steps: ["Curl with the thumbs facing up.", "Squeeze, then lower slowly."],
    formTips: ["Keep the wrists straight."],
    mistakes: ["Swinging", "Rotating the wrists"],
    easier: "Seated hammer curl",
    harder: "Cross-body hammer curl",
  }),
  make({
    id: "cable-curl",
    name: "Cable Curl",
    group: "biceps",
    targets: ["Biceps"],
    equipment: ["cable"],
    difficulty: "beginner",
    defaultSets: 3,
    defaultReps: "10-15",
    restSeconds: 60,
    met: 3,
    compound: false,
    setup: ["Attach a straight bar to a low pulley."],
    steps: ["Curl the bar up with constant tension.", "Lower slowly to full extension."],
    formTips: ["Stay upright.", "Keep tension through the whole set."],
    mistakes: ["Stepping too far from the pulley", "Using the back"],
    easier: "Lighter load",
    harder: "Single-arm cable curl",
  }),
  make({
    id: "triceps-pushdown",
    name: "Triceps Pushdown",
    group: "triceps",
    targets: ["Triceps"],
    equipment: ["cable"],
    difficulty: "beginner",
    defaultSets: 3,
    defaultReps: "10-15",
    restSeconds: 60,
    met: 3,
    compound: false,
    setup: ["Set a rope or bar at upper-chest height."],
    steps: [
      "Keep your elbows at your sides.",
      "Extend your arms fully.",
      "Return slowly to about 90 degrees.",
    ],
    formTips: ["Keep the torso still.", "Full lockout without slamming."],
    mistakes: ["Elbows drifting forward", "Leaning over the weight"],
    easier: "Lighter load with a rope",
    harder: "Single-arm reverse-grip pushdown",
  }),
  make({
    id: "skull-crusher",
    name: "Skull Crusher",
    group: "triceps",
    targets: ["Triceps"],
    equipment: ["barbell", "dumbbell"],
    difficulty: "intermediate",
    defaultSets: 3,
    defaultReps: "8-12",
    restSeconds: 90,
    met: 3,
    compound: false,
    setup: ["Lie on a bench holding an EZ-bar above your chest."],
    steps: [
      "Bend at the elbows to lower the bar towards your forehead.",
      "Stop just before contact.",
      "Extend back to the start.",
    ],
    formTips: ["Keep the upper arms still.", "Control the descent."],
    mistakes: ["Flaring the elbows", "Going too heavy too soon"],
    easier: "Dumbbell version with a neutral grip",
    harder: "Incline skull crusher",
  }),
  make({
    id: "overhead-extension",
    name: "Overhead Triceps Extension",
    group: "triceps",
    targets: ["Triceps (long head)"],
    equipment: ["dumbbell", "cable"],
    difficulty: "beginner",
    defaultSets: 3,
    defaultReps: "10-15",
    restSeconds: 75,
    met: 3,
    compound: false,
    setup: ["Hold a dumbbell overhead with both hands."],
    steps: [
      "Lower the weight behind your head.",
      "Feel a stretch in the triceps.",
      "Extend back overhead.",
    ],
    formTips: ["Keep the ribs down.", "Elbows point forward, not out."],
    mistakes: ["Arching the lower back", "Very fast reps"],
    easier: "Seated with back support",
    harder: "Single-arm cable overhead extension",
  }),
  make({
    id: "dips",
    name: "Parallel Bar Dips",
    group: "triceps",
    targets: ["Triceps", "Chest", "Front deltoids"],
    equipment: ["bodyweight"],
    difficulty: "advanced",
    defaultSets: 3,
    defaultReps: "6-12",
    restSeconds: 120,
    met: 5,
    compound: true,
    setup: ["Grip the bars and press to a locked-out support position."],
    steps: [
      "Lower until your upper arms are about parallel to the floor.",
      "Keep the elbows tracking back.",
      "Press back to lockout.",
    ],
    formTips: ["Stay tight through the core.", "Only descend as far as feels comfortable."],
    mistakes: ["Dropping too deep too soon", "Shrugging at the bottom"],
    easier: "Bench dip or assisted dip machine",
    harder: "Weighted dip",
  }),
  make({
    id: "squat",
    name: "Barbell Back Squat",
    group: "legs",
    targets: ["Quadriceps", "Glutes", "Core"],
    equipment: ["barbell"],
    difficulty: "intermediate",
    defaultSets: 4,
    defaultReps: "5-8",
    restSeconds: 180,
    tempo: "3-0-1",
    met: 6,
    compound: true,
    setup: [
      "Set the bar just below shoulder height.",
      "Position the bar on your upper back and unrack it.",
      "Take two steps back into a stable stance.",
    ],
    steps: [
      "Stand with feet approximately shoulder-width apart.",
      "Brace your core.",
      "Lower your body while keeping your chest controlled.",
      "Keep your knees tracking over your toes.",
      "Drive through your feet to return to the starting position.",
    ],
    formTips: [
      "Keep your spine controlled.",
      "Avoid uncontrolled movement.",
      "Use a weight you can safely control.",
    ],
    mistakes: [
      "Excessive weight",
      "Poor range of motion",
      "Knees collapsing inward",
      "Rising with the hips first",
    ],
    easier: "Goblet squat",
    harder: "Pause squat or front squat",
  }),
  make({
    id: "leg-press",
    name: "Leg Press",
    group: "legs",
    targets: ["Quadriceps", "Glutes"],
    equipment: ["machine"],
    difficulty: "beginner",
    defaultSets: 3,
    defaultReps: "10-15",
    restSeconds: 120,
    met: 5,
    compound: true,
    setup: ["Sit with your back and hips flat against the pad.", "Place feet shoulder-width on the platform."],
    steps: [
      "Release the safeties and lower the platform under control.",
      "Stop before your lower back rounds off the pad.",
      "Press back without locking the knees harshly.",
    ],
    formTips: ["Keep your heels down.", "Control the eccentric."],
    mistakes: ["Lowering too deep and rounding the back", "Bouncing the knees off the chest"],
    easier: "Lighter load with a shorter range",
    harder: "Single-leg press",
  }),
  make({
    id: "romanian-deadlift",
    name: "Romanian Deadlift",
    group: "legs",
    targets: ["Hamstrings", "Glutes", "Lower back"],
    equipment: ["barbell", "dumbbell"],
    difficulty: "intermediate",
    defaultSets: 3,
    defaultReps: "8-10",
    restSeconds: 120,
    met: 6,
    compound: true,
    setup: ["Hold the bar at hip height with a shoulder-width grip.", "Stand with feet hip-width apart."],
    steps: [
      "Soften the knees slightly and keep them fixed.",
      "Push your hips back and let the bar travel down your thighs.",
      "Stop when you feel a strong hamstring stretch.",
      "Drive your hips forward to stand tall.",
    ],
    formTips: ["Keep the bar close to your body.", "Maintain a neutral spine."],
    mistakes: ["Rounding the back", "Turning it into a squat", "Hyperextending at the top"],
    easier: "Dumbbell RDL with lighter load",
    harder: "Deficit or single-leg RDL",
  }),
  make({
    id: "lunge",
    name: "Walking Lunge",
    group: "legs",
    targets: ["Quadriceps", "Glutes"],
    equipment: ["dumbbell", "bodyweight"],
    difficulty: "beginner",
    defaultSets: 3,
    defaultReps: "10-12 per leg",
    restSeconds: 90,
    met: 5,
    compound: true,
    setup: ["Stand tall holding dumbbells at your sides."],
    steps: [
      "Step forward into a lunge.",
      "Lower until your back knee is just above the floor.",
      "Drive through the front foot to step through.",
    ],
    formTips: ["Keep your torso upright.", "Take a stride long enough to protect the front knee."],
    mistakes: ["Very short steps", "Letting the front knee collapse inward"],
    easier: "Static split squat holding a support",
    harder: "Deficit reverse lunge",
  }),
  make({
    id: "bulgarian-split-squat",
    name: "Bulgarian Split Squat",
    group: "legs",
    targets: ["Quadriceps", "Glutes"],
    equipment: ["dumbbell", "bodyweight"],
    difficulty: "intermediate",
    defaultSets: 3,
    defaultReps: "8-12 per leg",
    restSeconds: 90,
    met: 5,
    compound: true,
    setup: ["Place the top of your rear foot on a bench behind you."],
    steps: [
      "Set the front foot far enough forward to feel stable.",
      "Lower straight down.",
      "Drive back up through the front heel.",
    ],
    formTips: ["Lean the torso slightly forward for more glute involvement."],
    mistakes: ["Front foot too close to the bench", "Pushing off the back foot"],
    easier: "Split squat with both feet on the floor",
    harder: "Add dumbbells or slow the descent",
  }),
  make({
    id: "leg-extension",
    name: "Leg Extension",
    group: "legs",
    targets: ["Quadriceps"],
    equipment: ["machine"],
    difficulty: "beginner",
    defaultSets: 3,
    defaultReps: "12-15",
    restSeconds: 60,
    met: 4,
    compound: false,
    setup: ["Adjust the pad to sit just above the ankles."],
    steps: ["Extend your knees fully.", "Pause briefly.", "Lower slowly."],
    formTips: ["Avoid slamming the stack.", "Keep your hips down."],
    mistakes: ["Using momentum", "Excessively heavy load"],
    easier: "Lighter load with a pause",
    harder: "Single-leg extension",
  }),
  make({
    id: "leg-curl",
    name: "Leg Curl",
    group: "legs",
    targets: ["Hamstrings"],
    equipment: ["machine"],
    difficulty: "beginner",
    defaultSets: 3,
    defaultReps: "10-15",
    restSeconds: 60,
    met: 4,
    compound: false,
    setup: ["Align your knees with the machine pivot."],
    steps: ["Curl the pad towards your glutes.", "Pause, then return slowly."],
    formTips: ["Keep your hips down.", "Do not jerk the weight."],
    mistakes: ["Lifting the hips", "Partial range"],
    easier: "Seated leg curl",
    harder: "Nordic curl progression",
  }),
  make({
    id: "calf-raise",
    name: "Standing Calf Raise",
    group: "legs",
    targets: ["Calves"],
    equipment: ["machine", "bodyweight", "dumbbell"],
    difficulty: "beginner",
    defaultSets: 4,
    defaultReps: "12-20",
    restSeconds: 60,
    met: 3,
    compound: false,
    setup: ["Stand with the balls of your feet on a step."],
    steps: ["Rise as high as possible.", "Pause at the top.", "Lower until you feel a stretch."],
    formTips: ["Slow the lowering phase.", "Use a full range."],
    mistakes: ["Bouncing", "Very short reps"],
    easier: "Flat-floor calf raise",
    harder: "Single-leg weighted calf raise",
  }),
  make({
    id: "plank",
    name: "Plank",
    group: "core",
    targets: ["Deep core", "Abdominals"],
    equipment: ["bodyweight"],
    difficulty: "beginner",
    defaultSets: 3,
    defaultReps: "30-60 seconds",
    restSeconds: 60,
    met: 3,
    compound: false,
    setup: ["Set your elbows under your shoulders and forearms on the floor."],
    steps: [
      "Form a straight line from head to heels.",
      "Squeeze your glutes and brace your abs.",
      "Breathe steadily and hold.",
    ],
    formTips: ["Tuck the pelvis slightly.", "Keep the neck neutral."],
    mistakes: ["Hips sagging", "Holding your breath"],
    easier: "Plank from the knees",
    harder: "Long-lever or weighted plank",
    breathing:
      "Breathe shallowly and continuously through the hold — never hold your breath.",
  }),
  make({
    id: "side-plank",
    name: "Side Plank",
    group: "core",
    targets: ["Obliques", "Lateral core"],
    equipment: ["bodyweight"],
    difficulty: "beginner",
    defaultSets: 3,
    defaultReps: "20-45 seconds per side",
    restSeconds: 45,
    met: 3,
    compound: false,
    setup: ["Lie on your side with the elbow under the shoulder."],
    steps: ["Lift your hips into a straight line.", "Hold while breathing steadily.", "Lower with control."],
    formTips: ["Stack the shoulders and hips.", "Keep the neck long."],
    mistakes: ["Hips dropping", "Rotating forward"],
    easier: "Side plank from the knees",
    harder: "Side plank with a top-leg raise",
    breathing: "Keep breathing steadily throughout the hold.",
  }),
  make({
    id: "hanging-knee-raise",
    name: "Hanging Knee Raise",
    group: "core",
    targets: ["Lower abdominals", "Hip flexors"],
    equipment: ["bodyweight"],
    difficulty: "intermediate",
    defaultSets: 3,
    defaultReps: "8-15",
    restSeconds: 75,
    met: 4,
    compound: false,
    setup: ["Hang from a bar with active shoulders."],
    steps: ["Curl your knees up towards your chest.", "Pause briefly.", "Lower slowly without swinging."],
    formTips: ["Move slowly.", "Posteriorly tilt the pelvis at the top."],
    mistakes: ["Swinging the legs", "Using momentum"],
    easier: "Captain's chair knee raise",
    harder: "Straight-leg raise",
  }),
  make({
    id: "leg-raise",
    name: "Lying Leg Raise",
    group: "core",
    targets: ["Lower abdominals"],
    equipment: ["bodyweight"],
    difficulty: "beginner",
    defaultSets: 3,
    defaultReps: "10-15",
    restSeconds: 60,
    met: 3,
    compound: false,
    setup: ["Lie on your back with your hands beside your hips."],
    steps: [
      "Press your lower back into the floor.",
      "Raise your legs to vertical.",
      "Lower slowly without letting the back arch.",
    ],
    formTips: ["Stop the descent before the back lifts off."],
    mistakes: ["Arching the lower back", "Dropping the legs quickly"],
    easier: "Bent-knee leg raise",
    harder: "Hanging leg raise",
  }),
  make({
    id: "cable-crunch",
    name: "Cable Crunch",
    group: "core",
    targets: ["Abdominals"],
    equipment: ["cable"],
    difficulty: "beginner",
    defaultSets: 3,
    defaultReps: "12-15",
    restSeconds: 60,
    met: 3,
    compound: false,
    setup: ["Kneel below a high pulley holding a rope by your head."],
    steps: ["Crunch down by flexing the spine.", "Pause at the bottom.", "Return under control."],
    formTips: ["Keep the hips fixed.", "Move the ribs towards the pelvis."],
    mistakes: ["Turning it into a hip hinge", "Pulling with the arms"],
    easier: "Floor crunch",
    harder: "Slow tempo with a pause",
  }),
  make({
    id: "dead-bug",
    name: "Dead Bug",
    group: "core",
    targets: ["Deep core", "Coordination"],
    equipment: ["bodyweight"],
    difficulty: "beginner",
    defaultSets: 3,
    defaultReps: "8-10 per side",
    restSeconds: 45,
    met: 3,
    compound: false,
    setup: ["Lie on your back with arms up and knees bent at 90 degrees."],
    steps: [
      "Press your lower back gently into the floor.",
      "Lower the opposite arm and leg slowly.",
      "Return and switch sides.",
    ],
    formTips: ["Move slowly.", "Keep the ribs down."],
    mistakes: ["Letting the back arch", "Rushing the reps"],
    easier: "Move only the legs",
    harder: "Add a light weight in each hand",
    breathing: "Exhale as you extend, inhale as you return.",
  }),
];

export function getExercise(id: string): Exercise | undefined {
  return EXERCISES.find((exercise) => exercise.id === id);
}
