import type { Ingredient, Recipe } from "./types";

function ing(
  name: string,
  quantity: number,
  unit: string,
  category: Ingredient["category"],
): Ingredient {
  return { name, quantity, unit, category };
}

export const RECIPES: Recipe[] = [
  {
    id: "protein-oatmeal",
    name: "Protein Oatmeal with Berries",
    cuisine: "american",
    slots: ["breakfast"],
    servings: 1,
    prepMinutes: 10,
    calories: 450,
    proteinG: 35,
    carbsG: 55,
    fatG: 10,
    fiberG: 8,
    tags: ["high_protein", "vegetarian", "under_30", "budget", "breakfast"],
    ingredients: [
      ing("Rolled oats", 60, "g", "grains"),
      ing("Greek yogurt", 100, "g", "dairy"),
      ing("Whey or plant protein powder", 25, "g", "supplements"),
      ing("Banana", 1, "medium", "fruits"),
      ing("Mixed berries", 80, "g", "fruits"),
      ing("Peanut butter", 10, "g", "pantry"),
    ],
    instructions: [
      "Cook the oats with water or milk until creamy.",
      "Let them cool for a minute, then stir in the yogurt.",
      "Mix in the protein powder so it dissolves evenly.",
      "Top with sliced banana and berries.",
      "Finish with a spoon of peanut butter.",
    ],
    budgetFriendly: true,
    mealPrep: true,
  },
  {
    id: "overnight-oats",
    name: "Overnight Oats with Chia",
    cuisine: "american",
    slots: ["breakfast", "morning_snack"],
    servings: 1,
    prepMinutes: 5,
    calories: 400,
    proteinG: 25,
    carbsG: 52,
    fatG: 11,
    fiberG: 10,
    tags: ["vegetarian", "meal_prep", "under_30", "budget", "breakfast"],
    ingredients: [
      ing("Rolled oats", 50, "g", "grains"),
      ing("Milk or soy milk", 200, "ml", "dairy"),
      ing("Chia seeds", 10, "g", "pantry"),
      ing("Greek yogurt", 100, "g", "dairy"),
      ing("Honey", 8, "g", "pantry"),
      ing("Blueberries", 60, "g", "fruits"),
    ],
    instructions: [
      "Combine oats, milk and chia seeds in a jar.",
      "Stir through the yogurt and honey.",
      "Refrigerate overnight.",
      "Top with blueberries before eating.",
    ],
    budgetFriendly: true,
    mealPrep: true,
  },
  {
    id: "protein-pancakes",
    name: "Protein Pancakes",
    cuisine: "american",
    slots: ["breakfast"],
    servings: 1,
    prepMinutes: 15,
    calories: 480,
    proteinG: 40,
    carbsG: 50,
    fatG: 12,
    fiberG: 6,
    tags: ["high_protein", "vegetarian", "breakfast", "under_30"],
    ingredients: [
      ing("Oat flour", 50, "g", "grains"),
      ing("Egg whites", 150, "ml", "protein"),
      ing("Whole egg", 1, "each", "protein"),
      ing("Protein powder", 25, "g", "supplements"),
      ing("Baking powder", 3, "g", "pantry"),
      ing("Greek yogurt", 60, "g", "dairy"),
      ing("Strawberries", 80, "g", "fruits"),
    ],
    instructions: [
      "Blend the oat flour, egg whites, egg, protein powder and baking powder.",
      "Rest the batter for two minutes.",
      "Cook small pancakes over medium heat until bubbles form, then flip.",
      "Serve topped with yogurt and strawberries.",
    ],
    budgetFriendly: true,
    mealPrep: false,
  },
  {
    id: "chicken-bowl",
    name: "Grilled Chicken & Rice Bowl",
    cuisine: "american",
    slots: ["lunch", "dinner"],
    servings: 1,
    prepMinutes: 25,
    calories: 620,
    proteinG: 52,
    carbsG: 62,
    fatG: 16,
    fiberG: 7,
    tags: ["high_protein", "meal_prep", "gluten_free", "dairy_free", "lunch"],
    ingredients: [
      ing("Chicken breast", 180, "g", "protein"),
      ing("Cooked rice", 180, "g", "grains"),
      ing("Broccoli", 120, "g", "vegetables"),
      ing("Bell pepper", 1, "each", "vegetables"),
      ing("Olive oil", 10, "ml", "pantry"),
      ing("Paprika", 2, "g", "spices"),
      ing("Garlic powder", 2, "g", "spices"),
    ],
    instructions: [
      "Season the chicken with paprika, garlic powder, salt and pepper.",
      "Grill or pan-sear until cooked through, then rest and slice.",
      "Steam the broccoli and peppers until just tender.",
      "Build the bowl with rice, vegetables and sliced chicken.",
      "Finish with olive oil and a squeeze of lemon.",
    ],
    budgetFriendly: true,
    mealPrep: true,
  },
  {
    id: "turkey-sandwich",
    name: "Turkey & Avocado Sandwich",
    cuisine: "american",
    slots: ["lunch"],
    servings: 1,
    prepMinutes: 8,
    calories: 520,
    proteinG: 38,
    carbsG: 48,
    fatG: 18,
    fiberG: 9,
    tags: ["under_30", "budget", "lunch", "dairy_free"],
    ingredients: [
      ing("Wholegrain bread", 2, "slices", "grains"),
      ing("Sliced turkey breast", 120, "g", "protein"),
      ing("Avocado", 0.5, "each", "fruits"),
      ing("Tomato", 1, "each", "vegetables"),
      ing("Spinach", 30, "g", "vegetables"),
      ing("Mustard", 10, "g", "pantry"),
    ],
    instructions: [
      "Toast the bread.",
      "Spread mashed avocado and mustard across both slices.",
      "Layer the turkey, tomato and spinach.",
      "Close, slice and serve.",
    ],
    budgetFriendly: true,
    mealPrep: false,
  },
  {
    id: "healthy-burger",
    name: "Lean Beef Burger with Sweet Potato",
    cuisine: "american",
    slots: ["dinner"],
    servings: 1,
    prepMinutes: 30,
    calories: 680,
    proteinG: 45,
    carbsG: 62,
    fatG: 24,
    fiberG: 9,
    tags: ["high_protein", "dinner"],
    ingredients: [
      ing("Lean ground beef (5% fat)", 150, "g", "protein"),
      ing("Wholegrain burger bun", 1, "each", "grains"),
      ing("Sweet potato", 200, "g", "vegetables"),
      ing("Lettuce", 20, "g", "vegetables"),
      ing("Tomato", 1, "each", "vegetables"),
      ing("Olive oil", 8, "ml", "pantry"),
      ing("Smoked paprika", 2, "g", "spices"),
    ],
    instructions: [
      "Heat the oven to 200°C / 400°F.",
      "Toss sweet potato wedges with oil and paprika, roast 25 minutes.",
      "Shape the beef into a patty and season.",
      "Cook 3–4 minutes per side until done to your preference.",
      "Assemble the burger with lettuce and tomato and serve with the wedges.",
    ],
    budgetFriendly: false,
    mealPrep: false,
  },
  {
    id: "steak-veg",
    name: "Sirloin Steak with Roasted Vegetables",
    cuisine: "american",
    slots: ["dinner"],
    servings: 1,
    prepMinutes: 30,
    calories: 640,
    proteinG: 50,
    carbsG: 38,
    fatG: 30,
    fiberG: 8,
    tags: ["high_protein", "low_carb", "gluten_free", "dinner"],
    ingredients: [
      ing("Sirloin steak", 180, "g", "protein"),
      ing("Baby potatoes", 180, "g", "vegetables"),
      ing("Asparagus", 120, "g", "vegetables"),
      ing("Olive oil", 12, "ml", "pantry"),
      ing("Rosemary", 2, "g", "spices"),
    ],
    instructions: [
      "Roast the potatoes with oil and rosemary for 25 minutes.",
      "Sear the steak 3 minutes per side, then rest 5 minutes.",
      "Pan-roast the asparagus for 4 minutes.",
      "Slice the steak against the grain and plate everything.",
    ],
    budgetFriendly: false,
    mealPrep: false,
  },
  {
    id: "greek-yogurt-bowl",
    name: "Greek Yogurt & Walnut Bowl",
    cuisine: "american",
    slots: ["morning_snack", "afternoon_snack", "evening_snack"],
    servings: 1,
    prepMinutes: 3,
    calories: 260,
    proteinG: 24,
    carbsG: 20,
    fatG: 10,
    fiberG: 3,
    tags: ["high_protein", "vegetarian", "low_calorie", "under_30", "snack"],
    ingredients: [
      ing("Greek yogurt", 200, "g", "dairy"),
      ing("Walnuts", 12, "g", "pantry"),
      ing("Honey", 6, "g", "pantry"),
      ing("Raspberries", 60, "g", "fruits"),
    ],
    instructions: [
      "Spoon the yogurt into a bowl.",
      "Top with walnuts, raspberries and honey.",
    ],
    budgetFriendly: true,
    mealPrep: false,
  },
  {
    id: "chicken-tikka",
    name: "Chicken Tikka with Cucumber Salad",
    cuisine: "indian",
    slots: ["lunch", "dinner"],
    servings: 2,
    prepMinutes: 35,
    calories: 520,
    proteinG: 48,
    carbsG: 28,
    fatG: 22,
    fiberG: 5,
    tags: ["high_protein", "gluten_free", "dinner", "meal_prep"],
    ingredients: [
      ing("Chicken thigh, boneless", 400, "g", "protein"),
      ing("Greek yogurt", 150, "g", "dairy"),
      ing("Tikka spice blend", 12, "g", "spices"),
      ing("Ginger-garlic paste", 15, "g", "spices"),
      ing("Lemon", 1, "each", "fruits"),
      ing("Cucumber", 1, "each", "vegetables"),
      ing("Red onion", 0.5, "each", "vegetables"),
    ],
    instructions: [
      "Marinate the chicken in yogurt, spice blend, ginger-garlic paste and lemon for 20 minutes.",
      "Thread onto skewers or spread on a tray.",
      "Grill or bake at 220°C / 425°F for 15–18 minutes, turning once.",
      "Toss cucumber and onion with lemon juice and salt.",
      "Serve the tikka with the salad.",
    ],
    budgetFriendly: true,
    mealPrep: true,
  },
  {
    id: "tandoori-chicken",
    name: "Tandoori Chicken with Brown Rice",
    cuisine: "indian",
    slots: ["lunch", "dinner"],
    servings: 2,
    prepMinutes: 40,
    calories: 610,
    proteinG: 52,
    carbsG: 55,
    fatG: 18,
    fiberG: 6,
    tags: ["high_protein", "gluten_free", "meal_prep", "dinner"],
    ingredients: [
      ing("Chicken breast", 400, "g", "protein"),
      ing("Yogurt", 120, "g", "dairy"),
      ing("Tandoori masala", 12, "g", "spices"),
      ing("Brown rice, dry", 120, "g", "grains"),
      ing("Green beans", 150, "g", "vegetables"),
      ing("Lemon", 1, "each", "fruits"),
    ],
    instructions: [
      "Marinate the chicken in yogurt and tandoori masala for 30 minutes.",
      "Cook the rice according to the package.",
      "Bake the chicken at 220°C / 425°F for 20 minutes.",
      "Steam the green beans.",
      "Serve with lemon wedges.",
    ],
    budgetFriendly: true,
    mealPrep: true,
  },
  {
    id: "dal-tadka",
    name: "Dal Tadka with Rice",
    cuisine: "indian",
    slots: ["lunch", "dinner"],
    servings: 3,
    prepMinutes: 35,
    calories: 480,
    proteinG: 22,
    carbsG: 74,
    fatG: 11,
    fiberG: 14,
    tags: ["vegetarian", "vegan", "budget", "meal_prep", "gluten_free"],
    ingredients: [
      ing("Red lentils", 250, "g", "pantry"),
      ing("Onion", 1, "each", "vegetables"),
      ing("Tomato", 2, "each", "vegetables"),
      ing("Cumin seeds", 4, "g", "spices"),
      ing("Turmeric", 3, "g", "spices"),
      ing("Garlic", 4, "cloves", "vegetables"),
      ing("Basmati rice, dry", 180, "g", "grains"),
      ing("Ghee or oil", 15, "ml", "pantry"),
    ],
    instructions: [
      "Rinse the lentils and simmer with turmeric and water until soft.",
      "Cook the rice separately.",
      "Heat ghee, fry cumin seeds, garlic and onion until golden.",
      "Add tomato and cook down, then stir into the lentils.",
      "Simmer five more minutes and season to taste.",
    ],
    budgetFriendly: true,
    mealPrep: true,
  },
  {
    id: "rajma",
    name: "Rajma (Kidney Bean Curry)",
    cuisine: "indian",
    slots: ["lunch", "dinner"],
    servings: 3,
    prepMinutes: 40,
    calories: 520,
    proteinG: 24,
    carbsG: 78,
    fatG: 12,
    fiberG: 18,
    tags: ["vegetarian", "vegan", "budget", "high_fiber", "meal_prep"],
    ingredients: [
      ing("Kidney beans, cooked", 500, "g", "pantry"),
      ing("Onion", 1, "each", "vegetables"),
      ing("Tomato puree", 200, "g", "pantry"),
      ing("Garam masala", 5, "g", "spices"),
      ing("Ginger-garlic paste", 15, "g", "spices"),
      ing("Basmati rice, dry", 180, "g", "grains"),
      ing("Oil", 15, "ml", "pantry"),
    ],
    instructions: [
      "Fry the onion until deep golden.",
      "Add ginger-garlic paste and cook for a minute.",
      "Stir in tomato puree and garam masala and cook until thickened.",
      "Add the beans and a cup of water, simmer 15 minutes.",
      "Serve over rice.",
    ],
    budgetFriendly: true,
    mealPrep: true,
  },
  {
    id: "chana-masala",
    name: "Chana Masala",
    cuisine: "indian",
    slots: ["lunch", "dinner"],
    servings: 3,
    prepMinutes: 30,
    calories: 460,
    proteinG: 20,
    carbsG: 68,
    fatG: 12,
    fiberG: 16,
    tags: ["vegetarian", "vegan", "budget", "high_fiber", "gluten_free"],
    ingredients: [
      ing("Chickpeas, cooked", 500, "g", "pantry"),
      ing("Onion", 1, "each", "vegetables"),
      ing("Tomato", 3, "each", "vegetables"),
      ing("Chana masala spice", 8, "g", "spices"),
      ing("Basmati rice, dry", 150, "g", "grains"),
      ing("Oil", 15, "ml", "pantry"),
    ],
    instructions: [
      "Sauté the onion until soft.",
      "Add tomatoes and spice, cook until jammy.",
      "Add the chickpeas with a splash of water and simmer 10 minutes.",
      "Serve with rice or flatbread.",
    ],
    budgetFriendly: true,
    mealPrep: true,
  },
  {
    id: "paneer-bhurji",
    name: "Paneer Bhurji",
    cuisine: "indian",
    slots: ["breakfast", "dinner"],
    servings: 2,
    prepMinutes: 20,
    calories: 430,
    proteinG: 30,
    carbsG: 16,
    fatG: 28,
    fiberG: 4,
    tags: ["vegetarian", "high_protein", "low_carb", "gluten_free", "under_30"],
    ingredients: [
      ing("Paneer", 250, "g", "dairy"),
      ing("Onion", 1, "each", "vegetables"),
      ing("Tomato", 1, "each", "vegetables"),
      ing("Green chilli", 1, "each", "vegetables"),
      ing("Turmeric", 2, "g", "spices"),
      ing("Oil", 10, "ml", "pantry"),
    ],
    instructions: [
      "Crumble the paneer.",
      "Sauté onion, chilli and tomato until soft.",
      "Add turmeric and salt, then fold in the paneer.",
      "Cook two minutes and finish with coriander.",
    ],
    budgetFriendly: true,
    mealPrep: false,
  },
  {
    id: "veg-curry",
    name: "Mixed Vegetable Curry",
    cuisine: "indian",
    slots: ["lunch", "dinner"],
    servings: 3,
    prepMinutes: 30,
    calories: 380,
    proteinG: 12,
    carbsG: 52,
    fatG: 14,
    fiberG: 12,
    tags: ["vegetarian", "vegan", "low_calorie", "budget", "dairy_free"],
    ingredients: [
      ing("Cauliflower", 300, "g", "vegetables"),
      ing("Carrot", 2, "each", "vegetables"),
      ing("Peas", 150, "g", "vegetables"),
      ing("Coconut milk", 200, "ml", "pantry"),
      ing("Curry powder", 8, "g", "spices"),
      ing("Basmati rice, dry", 150, "g", "grains"),
    ],
    instructions: [
      "Sauté the vegetables for five minutes.",
      "Add curry powder and stir for 30 seconds.",
      "Pour in the coconut milk and simmer 15 minutes.",
      "Serve with rice.",
    ],
    budgetFriendly: true,
    mealPrep: true,
  },
  {
    id: "masala-egg-toast",
    name: "High-Protein Masala Egg Toast",
    cuisine: "indian",
    slots: ["breakfast"],
    servings: 1,
    prepMinutes: 12,
    calories: 420,
    proteinG: 28,
    carbsG: 34,
    fatG: 18,
    fiberG: 6,
    tags: ["high_protein", "vegetarian", "under_30", "budget", "breakfast"],
    ingredients: [
      ing("Eggs", 3, "each", "protein"),
      ing("Wholegrain bread", 2, "slices", "grains"),
      ing("Onion", 0.5, "each", "vegetables"),
      ing("Tomato", 1, "each", "vegetables"),
      ing("Chilli powder", 2, "g", "spices"),
      ing("Oil", 8, "ml", "pantry"),
    ],
    instructions: [
      "Whisk the eggs with chilli powder and salt.",
      "Sauté the onion and tomato until soft.",
      "Pour in the eggs and scramble gently.",
      "Serve on toasted bread.",
    ],
    budgetFriendly: true,
    mealPrep: false,
  },
  {
    id: "burrito-bowl",
    name: "Chicken Burrito Bowl",
    cuisine: "mexican",
    slots: ["lunch", "dinner"],
    servings: 1,
    prepMinutes: 25,
    calories: 650,
    proteinG: 50,
    carbsG: 65,
    fatG: 20,
    fiberG: 14,
    tags: ["high_protein", "meal_prep", "gluten_free", "lunch"],
    ingredients: [
      ing("Chicken breast", 170, "g", "protein"),
      ing("Cooked rice", 150, "g", "grains"),
      ing("Black beans", 120, "g", "pantry"),
      ing("Sweetcorn", 60, "g", "vegetables"),
      ing("Salsa", 60, "g", "pantry"),
      ing("Avocado", 0.5, "each", "fruits"),
      ing("Cumin", 3, "g", "spices"),
    ],
    instructions: [
      "Season and grill the chicken, then slice.",
      "Warm the beans with cumin.",
      "Layer rice, beans, corn and chicken in a bowl.",
      "Top with salsa and avocado.",
    ],
    budgetFriendly: true,
    mealPrep: true,
  },
  {
    id: "beef-tacos",
    name: "Lean Beef Tacos",
    cuisine: "mexican",
    slots: ["dinner"],
    servings: 2,
    prepMinutes: 20,
    calories: 560,
    proteinG: 42,
    carbsG: 48,
    fatG: 20,
    fiberG: 8,
    tags: ["high_protein", "under_30", "dinner"],
    ingredients: [
      ing("Lean ground beef", 300, "g", "protein"),
      ing("Corn tortillas", 6, "each", "grains"),
      ing("Onion", 1, "each", "vegetables"),
      ing("Taco seasoning", 12, "g", "spices"),
      ing("Lettuce", 60, "g", "vegetables"),
      ing("Lime", 1, "each", "fruits"),
    ],
    instructions: [
      "Brown the beef with the onion.",
      "Add the seasoning and a splash of water, simmer 5 minutes.",
      "Warm the tortillas.",
      "Fill with beef, lettuce and a squeeze of lime.",
    ],
    budgetFriendly: true,
    mealPrep: false,
  },
  {
    id: "chicken-fajitas",
    name: "Chicken Fajitas",
    cuisine: "mexican",
    slots: ["dinner"],
    servings: 2,
    prepMinutes: 25,
    calories: 540,
    proteinG: 46,
    carbsG: 46,
    fatG: 18,
    fiberG: 9,
    tags: ["high_protein", "dairy_free", "dinner"],
    ingredients: [
      ing("Chicken breast", 350, "g", "protein"),
      ing("Bell peppers", 2, "each", "vegetables"),
      ing("Onion", 1, "each", "vegetables"),
      ing("Tortillas", 4, "each", "grains"),
      ing("Fajita seasoning", 12, "g", "spices"),
      ing("Olive oil", 12, "ml", "pantry"),
    ],
    instructions: [
      "Slice the chicken and vegetables into strips.",
      "Sear the chicken in a hot pan, then set aside.",
      "Cook the peppers and onion until charred at the edges.",
      "Return the chicken with the seasoning and toss.",
      "Serve in warm tortillas.",
    ],
    budgetFriendly: true,
    mealPrep: true,
  },
  {
    id: "bean-bowl",
    name: "Black Bean & Quinoa Bowl",
    cuisine: "mexican",
    slots: ["lunch"],
    servings: 2,
    prepMinutes: 25,
    calories: 480,
    proteinG: 22,
    carbsG: 68,
    fatG: 14,
    fiberG: 18,
    tags: ["vegan", "vegetarian", "gluten_free", "high_fiber", "budget"],
    ingredients: [
      ing("Quinoa, dry", 120, "g", "grains"),
      ing("Black beans", 300, "g", "pantry"),
      ing("Cherry tomatoes", 150, "g", "vegetables"),
      ing("Avocado", 1, "each", "fruits"),
      ing("Lime", 1, "each", "fruits"),
      ing("Cumin", 3, "g", "spices"),
    ],
    instructions: [
      "Cook the quinoa and let it cool slightly.",
      "Warm the beans with cumin.",
      "Combine with tomatoes and sliced avocado.",
      "Dress with lime juice, salt and pepper.",
    ],
    budgetFriendly: true,
    mealPrep: true,
  },
  {
    id: "chicken-souvlaki",
    name: "Chicken Souvlaki Plate",
    cuisine: "mediterranean",
    slots: ["lunch", "dinner"],
    servings: 2,
    prepMinutes: 30,
    calories: 580,
    proteinG: 48,
    carbsG: 44,
    fatG: 22,
    fiberG: 7,
    tags: ["high_protein", "mediterranean", "dinner"],
    ingredients: [
      ing("Chicken breast", 400, "g", "protein"),
      ing("Greek yogurt", 120, "g", "dairy"),
      ing("Pita bread", 2, "each", "grains"),
      ing("Cucumber", 1, "each", "vegetables"),
      ing("Tomato", 2, "each", "vegetables"),
      ing("Olive oil", 15, "ml", "pantry"),
      ing("Oregano", 3, "g", "spices"),
    ],
    instructions: [
      "Marinate the diced chicken in oil, oregano, lemon and garlic.",
      "Skewer and grill until charred and cooked through.",
      "Mix yogurt with grated cucumber for a quick tzatziki.",
      "Serve with warm pita and chopped salad.",
    ],
    budgetFriendly: false,
    mealPrep: true,
  },
  {
    id: "greek-bowl",
    name: "Greek Chicken Bowl",
    cuisine: "mediterranean",
    slots: ["lunch"],
    servings: 1,
    prepMinutes: 20,
    calories: 560,
    proteinG: 45,
    carbsG: 45,
    fatG: 22,
    fiberG: 8,
    tags: ["high_protein", "mediterranean", "meal_prep", "lunch"],
    ingredients: [
      ing("Chicken breast", 160, "g", "protein"),
      ing("Couscous, dry", 60, "g", "grains"),
      ing("Feta", 30, "g", "dairy"),
      ing("Olives", 25, "g", "pantry"),
      ing("Cucumber", 0.5, "each", "vegetables"),
      ing("Cherry tomatoes", 100, "g", "vegetables"),
      ing("Olive oil", 10, "ml", "pantry"),
    ],
    instructions: [
      "Cook the couscous in hot stock and fluff with a fork.",
      "Grill the seasoned chicken and slice.",
      "Combine everything in a bowl.",
      "Dress with olive oil, lemon and oregano.",
    ],
    budgetFriendly: false,
    mealPrep: true,
  },
  {
    id: "baked-salmon",
    name: "Baked Salmon with Vegetables",
    cuisine: "mediterranean",
    slots: ["dinner"],
    servings: 1,
    prepMinutes: 25,
    calories: 600,
    proteinG: 42,
    carbsG: 38,
    fatG: 30,
    fiberG: 8,
    tags: ["high_protein", "pescatarian", "gluten_free", "dairy_free", "dinner"],
    ingredients: [
      ing("Salmon fillet", 180, "g", "protein"),
      ing("Baby potatoes", 180, "g", "vegetables"),
      ing("Courgette", 1, "each", "vegetables"),
      ing("Lemon", 1, "each", "fruits"),
      ing("Olive oil", 10, "ml", "pantry"),
      ing("Dill", 2, "g", "spices"),
    ],
    instructions: [
      "Roast the potatoes for 20 minutes at 200°C / 400°F.",
      "Add the salmon and courgette to the tray.",
      "Bake a further 12 minutes until the salmon flakes.",
      "Finish with lemon and dill.",
    ],
    budgetFriendly: false,
    mealPrep: false,
  },
  {
    id: "lentil-salad",
    name: "Lentil & Feta Salad",
    cuisine: "mediterranean",
    slots: ["lunch", "afternoon_snack"],
    servings: 2,
    prepMinutes: 15,
    calories: 420,
    proteinG: 22,
    carbsG: 46,
    fatG: 16,
    fiberG: 14,
    tags: ["vegetarian", "high_fiber", "under_30", "budget", "gluten_free"],
    ingredients: [
      ing("Cooked green lentils", 300, "g", "pantry"),
      ing("Feta", 60, "g", "dairy"),
      ing("Red onion", 0.5, "each", "vegetables"),
      ing("Cherry tomatoes", 150, "g", "vegetables"),
      ing("Parsley", 15, "g", "vegetables"),
      ing("Olive oil", 15, "ml", "pantry"),
    ],
    instructions: [
      "Combine the lentils, tomatoes, onion and parsley.",
      "Crumble the feta on top.",
      "Dress with olive oil, red wine vinegar, salt and pepper.",
    ],
    budgetFriendly: true,
    mealPrep: true,
  },
  {
    id: "chicken-stirfry",
    name: "Chicken & Vegetable Stir-Fry",
    cuisine: "asian",
    slots: ["lunch", "dinner"],
    servings: 2,
    prepMinutes: 20,
    calories: 560,
    proteinG: 46,
    carbsG: 58,
    fatG: 15,
    fiberG: 8,
    tags: ["high_protein", "under_30", "dairy_free", "meal_prep", "dinner"],
    ingredients: [
      ing("Chicken breast", 350, "g", "protein"),
      ing("Jasmine rice, dry", 130, "g", "grains"),
      ing("Broccoli", 200, "g", "vegetables"),
      ing("Carrot", 1, "each", "vegetables"),
      ing("Soy sauce", 25, "ml", "pantry"),
      ing("Sesame oil", 8, "ml", "pantry"),
      ing("Ginger", 8, "g", "spices"),
    ],
    instructions: [
      "Cook the rice.",
      "Sear the sliced chicken in a very hot wok.",
      "Add the vegetables and ginger, stir-fry three minutes.",
      "Add soy sauce and sesame oil, toss and serve over rice.",
    ],
    budgetFriendly: true,
    mealPrep: true,
  },
  {
    id: "teriyaki-tofu",
    name: "Teriyaki Tofu Bowl",
    cuisine: "asian",
    slots: ["lunch", "dinner"],
    servings: 2,
    prepMinutes: 25,
    calories: 520,
    proteinG: 28,
    carbsG: 66,
    fatG: 16,
    fiberG: 9,
    tags: ["vegan", "vegetarian", "dairy_free", "meal_prep"],
    ingredients: [
      ing("Firm tofu", 300, "g", "protein"),
      ing("Jasmine rice, dry", 130, "g", "grains"),
      ing("Edamame", 150, "g", "vegetables"),
      ing("Teriyaki sauce", 50, "ml", "pantry"),
      ing("Spring onion", 2, "each", "vegetables"),
      ing("Sesame seeds", 8, "g", "pantry"),
    ],
    instructions: [
      "Press and cube the tofu, then pan-fry until golden.",
      "Cook the rice and steam the edamame.",
      "Glaze the tofu with teriyaki sauce.",
      "Assemble and top with spring onion and sesame seeds.",
    ],
    budgetFriendly: true,
    mealPrep: true,
  },
  {
    id: "salmon-sushi-bowl",
    name: "Salmon Sushi-Inspired Bowl",
    cuisine: "asian",
    slots: ["lunch", "dinner"],
    servings: 1,
    prepMinutes: 20,
    calories: 610,
    proteinG: 40,
    carbsG: 62,
    fatG: 22,
    fiberG: 6,
    tags: ["pescatarian", "high_protein", "dairy_free", "lunch"],
    ingredients: [
      ing("Cooked salmon", 150, "g", "protein"),
      ing("Sushi rice, cooked", 180, "g", "grains"),
      ing("Cucumber", 0.5, "each", "vegetables"),
      ing("Avocado", 0.5, "each", "fruits"),
      ing("Nori sheet", 1, "each", "pantry"),
      ing("Soy sauce", 15, "ml", "pantry"),
    ],
    instructions: [
      "Season the warm rice with rice vinegar.",
      "Flake the salmon over the rice.",
      "Add sliced cucumber and avocado.",
      "Top with torn nori and a drizzle of soy sauce.",
    ],
    budgetFriendly: false,
    mealPrep: false,
  },
  {
    id: "beef-noodles",
    name: "Beef & Rice Noodle Bowl",
    cuisine: "asian",
    slots: ["dinner"],
    servings: 2,
    prepMinutes: 25,
    calories: 620,
    proteinG: 44,
    carbsG: 72,
    fatG: 17,
    fiberG: 6,
    tags: ["high_protein", "gluten_free", "dairy_free", "dinner"],
    ingredients: [
      ing("Lean beef strips", 300, "g", "protein"),
      ing("Rice noodles, dry", 150, "g", "grains"),
      ing("Pak choi", 200, "g", "vegetables"),
      ing("Garlic", 3, "cloves", "vegetables"),
      ing("Soy sauce", 30, "ml", "pantry"),
      ing("Chilli flakes", 2, "g", "spices"),
    ],
    instructions: [
      "Soak the noodles until tender, then drain.",
      "Sear the beef quickly over high heat.",
      "Add garlic and pak choi and cook two minutes.",
      "Toss through the noodles with soy sauce and chilli.",
    ],
    budgetFriendly: true,
    mealPrep: false,
  },
  {
    id: "chicken-shawarma",
    name: "Chicken Shawarma Plate",
    cuisine: "middle_eastern",
    slots: ["lunch", "dinner"],
    servings: 2,
    prepMinutes: 30,
    calories: 590,
    proteinG: 48,
    carbsG: 48,
    fatG: 22,
    fiberG: 9,
    tags: ["high_protein", "halal", "meal_prep", "dinner"],
    ingredients: [
      ing("Chicken thigh, boneless", 400, "g", "protein"),
      ing("Shawarma spice", 12, "g", "spices"),
      ing("Flatbread", 2, "each", "grains"),
      ing("Tomato", 2, "each", "vegetables"),
      ing("Cucumber", 1, "each", "vegetables"),
      ing("Tahini", 25, "g", "pantry"),
      ing("Garlic", 2, "cloves", "vegetables"),
    ],
    instructions: [
      "Toss the chicken with shawarma spice, oil and lemon.",
      "Roast at 220°C / 425°F for 20 minutes, then slice.",
      "Thin the tahini with water, lemon and garlic.",
      "Serve with flatbread, salad and tahini sauce.",
    ],
    budgetFriendly: true,
    mealPrep: true,
  },
  {
    id: "hummus-bowl",
    name: "Hummus & Falafel Bowl",
    cuisine: "middle_eastern",
    slots: ["lunch"],
    servings: 2,
    prepMinutes: 20,
    calories: 520,
    proteinG: 20,
    carbsG: 62,
    fatG: 22,
    fiberG: 15,
    tags: ["vegetarian", "vegan", "high_fiber", "budget", "lunch"],
    ingredients: [
      ing("Hummus", 150, "g", "pantry"),
      ing("Falafel", 8, "pieces", "protein"),
      ing("Cooked bulgur", 200, "g", "grains"),
      ing("Tomato", 2, "each", "vegetables"),
      ing("Parsley", 20, "g", "vegetables"),
      ing("Olive oil", 12, "ml", "pantry"),
    ],
    instructions: [
      "Warm the falafel in the oven.",
      "Spoon bulgur into bowls and add a generous swipe of hummus.",
      "Add falafel, chopped tomato and parsley.",
      "Drizzle with olive oil and lemon.",
    ],
    budgetFriendly: true,
    mealPrep: true,
  },
  {
    id: "lamb-kebab",
    name: "Grilled Kebabs with Salad",
    cuisine: "middle_eastern",
    slots: ["dinner"],
    servings: 2,
    prepMinutes: 30,
    calories: 560,
    proteinG: 44,
    carbsG: 30,
    fatG: 28,
    fiberG: 6,
    tags: ["high_protein", "halal", "low_carb", "gluten_free", "dinner"],
    ingredients: [
      ing("Lean lamb or beef mince", 350, "g", "protein"),
      ing("Onion", 1, "each", "vegetables"),
      ing("Parsley", 20, "g", "vegetables"),
      ing("Baharat spice", 8, "g", "spices"),
      ing("Tomato", 2, "each", "vegetables"),
      ing("Cucumber", 1, "each", "vegetables"),
    ],
    instructions: [
      "Blend the onion and parsley into the mince with the spice.",
      "Shape onto skewers and chill 10 minutes.",
      "Grill 8–10 minutes, turning regularly.",
      "Serve with chopped salad.",
    ],
    budgetFriendly: false,
    mealPrep: false,
  },
  {
    id: "mujadara",
    name: "Lentils & Rice with Crispy Onion",
    cuisine: "middle_eastern",
    slots: ["lunch", "dinner"],
    servings: 3,
    prepMinutes: 35,
    calories: 450,
    proteinG: 16,
    carbsG: 72,
    fatG: 12,
    fiberG: 12,
    tags: ["vegan", "vegetarian", "budget", "high_fiber", "meal_prep"],
    ingredients: [
      ing("Green lentils, dry", 180, "g", "pantry"),
      ing("Basmati rice, dry", 150, "g", "grains"),
      ing("Onion", 2, "each", "vegetables"),
      ing("Cumin", 4, "g", "spices"),
      ing("Olive oil", 20, "ml", "pantry"),
    ],
    instructions: [
      "Simmer the lentils until almost tender.",
      "Fry the sliced onion slowly until deeply golden.",
      "Add rice, cumin and water to the lentils and cook covered 15 minutes.",
      "Rest, fluff and top with the crispy onion.",
    ],
    budgetFriendly: true,
    mealPrep: true,
  },
  {
    id: "cottage-cheese-toast",
    name: "Cottage Cheese Toast",
    cuisine: "american",
    slots: ["morning_snack", "afternoon_snack", "breakfast"],
    servings: 1,
    prepMinutes: 5,
    calories: 300,
    proteinG: 26,
    carbsG: 28,
    fatG: 8,
    fiberG: 5,
    tags: ["high_protein", "vegetarian", "under_30", "budget", "snack"],
    ingredients: [
      ing("Cottage cheese", 180, "g", "dairy"),
      ing("Wholegrain bread", 1, "slice", "grains"),
      ing("Tomato", 1, "each", "vegetables"),
      ing("Black pepper", 1, "g", "spices"),
    ],
    instructions: [
      "Toast the bread.",
      "Spread the cottage cheese thickly.",
      "Top with sliced tomato and black pepper.",
    ],
    budgetFriendly: true,
    mealPrep: false,
  },
  {
    id: "protein-smoothie",
    name: "Berry Protein Smoothie",
    cuisine: "american",
    slots: ["morning_snack", "afternoon_snack", "evening_snack"],
    servings: 1,
    prepMinutes: 5,
    calories: 280,
    proteinG: 30,
    carbsG: 28,
    fatG: 5,
    fiberG: 5,
    tags: ["high_protein", "low_calorie", "vegetarian", "under_30", "snack"],
    ingredients: [
      ing("Protein powder", 30, "g", "supplements"),
      ing("Frozen berries", 120, "g", "fruits"),
      ing("Milk or soy milk", 250, "ml", "dairy"),
      ing("Banana", 0.5, "each", "fruits"),
    ],
    instructions: ["Add everything to a blender.", "Blend until smooth."],
    budgetFriendly: true,
    mealPrep: false,
  },
  {
    id: "edamame-snack",
    name: "Sea Salt Edamame",
    cuisine: "asian",
    slots: ["afternoon_snack", "evening_snack"],
    servings: 1,
    prepMinutes: 6,
    calories: 190,
    proteinG: 17,
    carbsG: 14,
    fatG: 8,
    fiberG: 8,
    tags: ["vegan", "vegetarian", "low_calorie", "gluten_free", "snack"],
    ingredients: [
      ing("Edamame in pods", 200, "g", "vegetables"),
      ing("Sea salt", 2, "g", "spices"),
    ],
    instructions: [
      "Boil or steam the edamame for five minutes.",
      "Drain and toss with sea salt.",
    ],
    budgetFriendly: true,
    mealPrep: false,
  },
  {
    id: "casein-yogurt",
    name: "Evening Yogurt & Almonds",
    cuisine: "american",
    slots: ["evening_snack"],
    servings: 1,
    prepMinutes: 3,
    calories: 240,
    proteinG: 22,
    carbsG: 14,
    fatG: 11,
    fiberG: 3,
    tags: ["high_protein", "vegetarian", "low_calorie", "gluten_free", "snack"],
    ingredients: [
      ing("Greek yogurt", 170, "g", "dairy"),
      ing("Almonds", 15, "g", "pantry"),
      ing("Cinnamon", 1, "g", "spices"),
    ],
    instructions: [
      "Spoon the yogurt into a bowl.",
      "Top with almonds and a pinch of cinnamon.",
    ],
    budgetFriendly: true,
    mealPrep: false,
  },
];

export function getRecipe(id: string): Recipe | undefined {
  return RECIPES.find((recipe) => recipe.id === id);
}
